# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "E:\Programy\CLion\CLion 2017.3.3\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "E:\Programy\CLion\CLion 2017.3.3\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Piotrek\Desktop\SNAKEDELUXE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Piotrek\Desktop\SNAKEDELUXE\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"E:\Programy\CLion\CLion 2017.3.3\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"E:\Programy\CLion\CLion 2017.3.3\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Piotrek\Desktop\SNAKEDELUXE\cmake-build-debug\CMakeFiles C:\Users\Piotrek\Desktop\SNAKEDELUXE\cmake-build-debug\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Piotrek\Desktop\SNAKEDELUXE\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SNAKEDELUXE

# Build rule for target.
SNAKEDELUXE: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 SNAKEDELUXE
.PHONY : SNAKEDELUXE

# fast build rule for target.
SNAKEDELUXE/fast:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/build
.PHONY : SNAKEDELUXE/fast

Game.obj: Game.cpp.obj

.PHONY : Game.obj

# target to build an object file
Game.cpp.obj:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Game.cpp.obj
.PHONY : Game.cpp.obj

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Game.cpp.s
.PHONY : Game.cpp.s

Plansza.obj: Plansza.cpp.obj

.PHONY : Plansza.obj

# target to build an object file
Plansza.cpp.obj:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Plansza.cpp.obj
.PHONY : Plansza.cpp.obj

Plansza.i: Plansza.cpp.i

.PHONY : Plansza.i

# target to preprocess a source file
Plansza.cpp.i:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Plansza.cpp.i
.PHONY : Plansza.cpp.i

Plansza.s: Plansza.cpp.s

.PHONY : Plansza.s

# target to generate assembly for a file
Plansza.cpp.s:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Plansza.cpp.s
.PHONY : Plansza.cpp.s

Pole.obj: Pole.cpp.obj

.PHONY : Pole.obj

# target to build an object file
Pole.cpp.obj:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Pole.cpp.obj
.PHONY : Pole.cpp.obj

Pole.i: Pole.cpp.i

.PHONY : Pole.i

# target to preprocess a source file
Pole.cpp.i:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Pole.cpp.i
.PHONY : Pole.cpp.i

Pole.s: Pole.cpp.s

.PHONY : Pole.s

# target to generate assembly for a file
Pole.cpp.s:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Pole.cpp.s
.PHONY : Pole.cpp.s

Snake.obj: Snake.cpp.obj

.PHONY : Snake.obj

# target to build an object file
Snake.cpp.obj:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Snake.cpp.obj
.PHONY : Snake.cpp.obj

Snake.i: Snake.cpp.i

.PHONY : Snake.i

# target to preprocess a source file
Snake.cpp.i:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Snake.cpp.i
.PHONY : Snake.cpp.i

Snake.s: Snake.cpp.s

.PHONY : Snake.s

# target to generate assembly for a file
Snake.cpp.s:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/Snake.cpp.s
.PHONY : Snake.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\SNAKEDELUXE.dir\build.make CMakeFiles/SNAKEDELUXE.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... SNAKEDELUXE
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Game.obj
	@echo ... Game.i
	@echo ... Game.s
	@echo ... Plansza.obj
	@echo ... Plansza.i
	@echo ... Plansza.s
	@echo ... Pole.obj
	@echo ... Pole.i
	@echo ... Pole.s
	@echo ... Snake.obj
	@echo ... Snake.i
	@echo ... Snake.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

